---
- name: Check hosts
  hosts: localhost
  vars:
    server: "{{ structure_vars }}"
  tasks:    
  - set_fact:
     server1: '{{ server | from_yaml }}'
  - name: Print a var
    debug:
      msg: "{{ server1[0].Unit }}"
  
    
