---
- name: Check hosts
  hosts: localhost
  vars:
    server: "{{ structure_vars }}"
  tasks:    
  - set_fact:
     server1: '{{ server | from_yaml }}'
  - name: Print a var
    debug:
      msg: "Name : {{ item.Unit }}, Size: {{ item.Size }}"
    loop: "{{ server1 }}"
  
    
