---
- name: Check hosts
  hosts: localhost
  vars:
    peoples:
      kittipod:
        no: 0284
      supakkavee:
        no: 2085
    admin: kittipod
  tasks:
  - name: Print a var
    debug:
      msg: "{{ peoples[admin]['no'] }}"
  
    
